const URL = import.meta.env.VITE_SUPABASE_URL || "https://whsrmezqiguwkjltonox.supabase.co";
const KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "";
const TOKEN_KEY = "artistas-do-bairro-auth";
type Session = { access_token: string; refresh_token: string; user: { id: string; email?: string; user_metadata?: Record<string, unknown> } };
function headers(token?: string) { return { apikey: KEY, Authorization: `Bearer ${token || KEY}`, "Content-Type": "application/json" }; }
async function authRequest(path: string, body?: unknown) { const r = await fetch(`${URL}/auth/v1/${path}`, { method: "POST", headers: headers(), body: body === undefined ? undefined : JSON.stringify(body) }); const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.msg || data.error_description || data.message || "Não foi possível concluir o acesso."); return data; }
export async function signUp(email: string, password: string, name: string, phone: string) { const data = await authRequest("signup", { email, password, data: { name, phone } }); if (data.access_token) saveSession(data as Session); return data as Session; }
export async function signIn(email: string, password: string) { const data = await authRequest("token?grant_type=password", { email, password }); saveSession(data as Session); return data as Session; }
export async function signOut() { const s = getSession(); if (s?.access_token) await fetch(`${URL}/auth/v1/logout`, { method: "POST", headers: headers(s.access_token) }); localStorage.removeItem(TOKEN_KEY); }
export function getSession(): Session | null { try { return JSON.parse(localStorage.getItem(TOKEN_KEY) || "null"); } catch { return null; } }
function saveSession(s: Session) { localStorage.setItem(TOKEN_KEY, JSON.stringify(s)); }
export async function api(path: string, options: RequestInit = {}) { const s = getSession(); const h = new Headers(options.headers); h.set("apikey", KEY); h.set("Authorization", `Bearer ${s?.access_token || KEY}`); h.set("Content-Type", "application/json"); const r = await fetch(`${URL}/rest/v1/${path}`, { ...options, headers: h }); const data = await r.json().catch(() => null); if (!r.ok) throw new Error(data?.message || data?.hint || "Erro no banco de dados."); return data; }
export async function getProfile() { const s = getSession(); if (!s) return null; const rows = await api(`profiles?id=eq.${encodeURIComponent(s.user.id)}&select=*,artist_profiles(*)`); return rows?.[0] || null; }
export async function updateProfile(values: Record<string, unknown>) { const s = getSession(); if (!s) throw new Error("Faça login primeiro."); return api(`profiles?id=eq.${encodeURIComponent(s.user.id)}`, { method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify(values) }); }
export async function applyAsArtist(values: Record<string, unknown>) { const s = getSession(); if (!s) throw new Error("Faça login primeiro."); return api("artist_profiles", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify({ user_id: s.user.id, ...values, status: "pending" }) }); }
export async function updateArtist(values: Record<string, unknown>) { const s = getSession(); if (!s) throw new Error("Faça login primeiro."); return api(`artist_profiles?user_id=eq.${encodeURIComponent(s.user.id)}`, { method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify(values) }); }
