import { FormEvent, useEffect, useState } from "react";
import { Image as ImageIcon, LogOut, Save, Sparkles, X } from "lucide-react";
import { getProfile, signOut, updateProfile, applyAsArtist, updateArtist } from "../lib/auth";

export function AccountPanel({ open, onClose, onLoggedOut }: { open: boolean; onClose: () => void; onLoggedOut: () => void }) {
 const [name,setName]=useState(""),[phone,setPhone]=useState(""),[city,setCity]=useState(""),[avatar,setAvatar]=useState(""),[avatarBroken,setAvatarBroken]=useState(false),[artist,setArtist]=useState<any>(null),[bio,setBio]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{if(open)getProfile().then(p=>{setName(p?.display_name||"");setPhone(p?.phone||"");setCity(p?.city||"");setAvatar(p?.avatar_url||"");setAvatarBroken(false);setArtist(p?.artist_profiles?.[0]||null);setBio(p?.artist_profiles?.[0]?.bio||"")}).catch(()=>{})},[open]);
 useEffect(()=>{setAvatarBroken(false)},[avatar]);
 if(!open)return null;
 const initials=(name||"Usuário").trim().split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase();
 const save=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");try{await updateProfile({display_name:name.trim(),phone:phone.trim(),city:city.trim(),avatar_url:avatar.trim()||null});window.dispatchEvent(new CustomEvent("profile-updated"));setMessage("Perfil atualizado e foto salva.")}catch(err){setMessage(err instanceof Error?err.message:"Erro ao salvar o perfil.")}finally{setBusy(false)}};
 const artistSave=async()=>{setBusy(true);setMessage("");try{if(artist)await updateArtist({display_name:name.trim(),bio:bio.trim(),city:city.trim(),photo_url:avatar.trim()||null});else await applyAsArtist({display_name:name.trim(),bio:bio.trim(),city:city.trim(),photo_url:avatar.trim()||null,cover_url:avatar.trim()||null,price:0,category_id:null});setMessage("Perfil de artista enviado para análise.");setArtist((current:any)=>({...current,status:"pending"}))}catch(err){setMessage(err instanceof Error?err.message:"Não foi possível criar o perfil de artista.")}finally{setBusy(false)}};
 return <div className="fixed inset-0 z-[75] overflow-y-auto bg-black/70 p-4 backdrop-blur-md"><div className="mx-auto my-6 w-full max-w-2xl rounded-3xl border border-line bg-surface p-6 shadow-2xl sm:p-8">
   <div className="flex items-start justify-between gap-4"><div className="flex min-w-0 items-center gap-4"><div className="relative h-20 w-20 shrink-0 overflow-hidden rounded-full border-2 border-accent bg-accent-soft shadow-lg">{avatar&&!avatarBroken?<img src={avatar} alt={`Foto de perfil de ${name||"usuário"}`} className="h-full w-full object-cover" onError={()=>setAvatarBroken(true)} referrerPolicy="no-referrer"/>:<div className="grid h-full w-full place-items-center font-display text-xl font-extrabold text-accent">{initials||<ImageIcon className="h-7 w-7"/>}</div>}</div><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-widest text-accent">Minha conta</p><h2 className="mt-1 break-words font-display text-2xl font-extrabold sm:text-3xl">{name||"Usuário"}</h2><p className="mt-1 text-sm text-ink-soft">Sua foto de perfil aparece aqui.</p></div></div><button onClick={onClose} className="grid h-10 w-10 shrink-0 place-items-center rounded-full border border-line" aria-label="Fechar"><X className="h-5 w-5"/></button></div>
   <form onSubmit={save} className="mt-7 grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold">Nome<input value={name} onChange={e=>setName(e.target.value)} className="mt-1.5 w-full rounded-2xl border border-line bg-bg-soft px-4 py-3 outline-none focus:border-accent"/></label><label className="text-xs font-semibold">Telefone<input value={phone} onChange={e=>setPhone(e.target.value)} className="mt-1.5 w-full rounded-2xl border border-line bg-bg-soft px-4 py-3 outline-none focus:border-accent"/></label><label className="text-xs font-semibold">Cidade<input value={city} onChange={e=>setCity(e.target.value)} className="mt-1.5 w-full rounded-2xl border border-line bg-bg-soft px-4 py-3 outline-none focus:border-accent"/></label><label className="text-xs font-semibold sm:col-span-2">Endereço da foto de perfil<input value={avatar} onChange={e=>{setAvatar(e.target.value);setAvatarBroken(false)}} className="mt-1.5 w-full rounded-2xl border border-line bg-bg-soft px-4 py-3 outline-none focus:border-accent" placeholder="https://exemplo.com/minha-foto.jpg" inputMode="url"/><span className="mt-1.5 block text-[11px] font-normal leading-5 text-ink-soft">Use o endereço direto do arquivo da imagem (.jpg, .jpeg, .png ou .webp).</span></label>
   <div className="flex items-center gap-3 rounded-2xl border border-line bg-bg-soft p-3 sm:col-span-2"><div className="h-14 w-14 shrink-0 overflow-hidden rounded-xl bg-surface">{avatar&&!avatarBroken?<img src={avatar} alt="Prévia da foto" className="h-full w-full object-cover" onError={()=>setAvatarBroken(true)} referrerPolicy="no-referrer"/>:<div className="grid h-full w-full place-items-center text-ink-soft"><ImageIcon className="h-5 w-5"/></div>}</div><div className="min-w-0 text-xs text-ink-soft"><p className="font-semibold text-ink">Prévia da foto</p><p className="mt-0.5 break-words">{avatarBroken?"Não foi possível carregar esta imagem. Use um endereço que aponte diretamente para o arquivo.":avatar?"Imagem carregada com sucesso.":"Digite um endereço acima para visualizar a foto."}</p></div></div>
   <button disabled={busy} className="sm:col-span-2 flex items-center justify-center gap-2 rounded-2xl bg-accent px-5 py-3 font-bold text-accent-ink disabled:opacity-60"><Save className="h-4 w-4"/>{busy?"Salvando...":"Salvar perfil"}</button></form>
   {message&&<p className="mt-4 rounded-xl bg-accent-soft p-3 text-sm font-semibold text-accent" role="status">{message}</p>}
   <div className="mt-8 rounded-3xl border border-line bg-bg-soft p-5"><div className="flex items-start gap-3"><Sparkles className="mt-1 shrink-0 text-accent"/><div className="min-w-0"><h3 className="font-display text-xl font-bold">{artist?"Seu perfil de artista":"Quero ser artista"}</h3><p className="mt-1 text-sm text-ink-soft">{artist?`Status: ${artist.status}`:"Transforme sua conta em um perfil profissional."}</p></div></div><textarea value={bio} onChange={e=>setBio(e.target.value)} placeholder="Conte sobre seu trabalho..." className="mt-4 min-h-28 w-full rounded-2xl border border-line bg-surface p-4 text-sm outline-none focus:border-accent"/><button type="button" onClick={artistSave} disabled={busy} className="mt-4 rounded-2xl bg-ink px-5 py-3 text-sm font-bold text-bg disabled:opacity-60 dark:bg-accent dark:text-accent-ink">{artist?"Salvar perfil de artista":"Solicitar perfil de artista"}</button></div>
   <button onClick={async()=>{await signOut();onLoggedOut();onClose()}} className="mt-6 flex items-center gap-2 text-sm font-bold text-red-500"><LogOut className="h-4 w-4"/>Sair da conta</button>
 </div></div>;
}
