import { FormEvent, useEffect, useState } from "react";
import { LogOut, Save, Sparkles, X } from "lucide-react";
import { getProfile, signOut, updateProfile, applyAsArtist, updateArtist } from "../lib/auth";
export function AccountPanel({open,onClose,onLoggedOut}:{open:boolean;onClose:()=>void;onLoggedOut:()=>void}){
 const [name,setName]=useState(""),[phone,setPhone]=useState(""),[city,setCity]=useState(""),[avatar,setAvatar]=useState(""),[artist,setArtist]=useState<any>(null),[bio,setBio]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{if(open)getProfile().then(p=>{setName(p?.display_name||"");setPhone(p?.phone||"");setCity(p?.city||"");setAvatar(p?.avatar_url||"");setArtist(p?.artist_profiles?.[0]||null);setBio(p?.artist_profiles?.[0]?.bio||"")}).catch(()=>{})},[open]);
 if(!open)return null;
 const save=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{await updateProfile({display_name:name,phone,city,avatar_url:avatar});setMessage("Perfil atualizado.")}catch(err){setMessage(err instanceof Error?err.message:"Erro ao salvar.")}finally{setBusy(false)}};
 const artistSave=async()=>{setBusy(true);try{if(artist)await updateArtist({display_name:name,bio,city,photo_url:avatar});else await applyAsArtist({display_name:name,bio,city,photo_url:avatar,cover_url:avatar,price:0,category_id:null});setMessage("Perfil de artista enviado para análise.");setArtist({...artist,status:"pending"})}catch(err){setMessage(err instanceof Error?err.message:"Não foi possível criar o perfil de artista.")}finally{setBusy(false)}};
 return <div className="fixed inset-0 z-[75] overflow-y-auto bg-black/70 p-4 backdrop-blur-md"><div className="mx-auto my-6 w-full max-w-2xl rounded-3xl border border-line bg-surface p-6 shadow-2xl sm:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-accent">Minha conta</p><h2 className="mt-1 font-display text-3xl font-extrabold">Olá, {name||"usuário"}.</h2></div><button onClick={onClose} className="grid h-10 w-10 place-items-center rounded-full border border-line"><X/></button></div><form onSubmit={save} className="mt-7 grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold">Nome<input value={name} onChange={e=>setName(e.target.value)} className="mt-1.5 w-full rounded-2xl border border-line bg-bg-soft px-4 py-3"/></label><label className="text-xs font-semibold">Telefone<input value={phone} onChange={e=>setPhone(e.target.value)} className="mt-1.5 w-full rounded-2xl border border-line bg-bg-soft px-4 py-3"/></label><label className="text-xs font-semibold">Cidade<input value={city} onChange={e=>setCity(e.target.value)} className="mt-1.5 w-full rounded-2xl border border-line bg-bg-soft px-4 py-3"/></label><label className="text-xs font-semibold">URL da foto<input value={avatar} onChange={e=>setAvatar(e.target.value)} className="mt-1.5 w-full rounded-2xl border border-line bg-bg-soft px-4 py-3" placeholder="https://..."/></label><button disabled={busy} className="sm:col-span-2 flex items-center justify-center gap-2 rounded-2xl bg-accent px-5 py-3 font-bold text-accent-ink"><Save className="h-4 w-4"/>{busy?"Salvando...":"Salvar perfil"}</button></form>{message&&<p className="mt-4 rounded-xl bg-accent-soft p-3 text-sm font-semibold text-accent">{message}</p>}<div className="mt-8 rounded-3xl border border-line bg-bg-soft p-5"><div className="flex items-center gap-3"><Sparkles className="text-accent"/><div><h3 className="font-display text-xl font-bold">{artist?"Seu perfil de artista":"Quero ser artista"}</h3><p className="text-sm text-ink-soft">{artist?`Status: ${artist.status}`:"Transforme sua conta em um perfil profissional."}</p></div></div><textarea value={bio} onChange={e=>setBio(e.target.value)} placeholder="Conte sobre seu trabalho..." className="mt-4 min-h-28 w-full rounded-2xl border border-line bg-surface p-4 text-sm"/><button type="button" onClick={artistSave} disabled={busy} className="mt-4 rounded-2xl bg-ink px-5 py-3 text-sm font-bold text-bg dark:bg-accent dark:text-accent-ink">{artist?"Salvar perfil de artista":"Solicitar perfil de artista"}</button></div><button onClick={async()=>{await signOut();onLoggedOut();onClose()}} className="mt-6 flex items-center gap-2 text-sm font-bold text-red-500"><LogOut className="h-4 w-4"/>Sair da conta</button></div></div>;
}