import { useEffect, useState } from "react";
import { Menu, X, Sparkles, UserRound } from "lucide-react";
import { Logo } from "./ui/Brand";
import { getProfile } from "../lib/auth";
import { useScrollY } from "../hooks/useTheme";
import { cn } from "../utils/cn";
const LINKS=[{href:"#categorias",label:"Categorias"},{href:"#artistas",label:"Artistas"},{href:"#como-funciona",label:"Como funciona"},{href:"#depoimentos",label:"Depoimentos"}];
export function scrollToId(id:string){const el=document.querySelector(id);if(!el)return;const reduce=window.matchMedia("(prefers-reduced-motion: reduce)").matches;window.scrollTo({top:el.getBoundingClientRect().top+window.scrollY-84,behavior:reduce?"auto":"smooth"})}
export function Navbar({onLogin,onArtistLogin,onAccount,loggedIn}:{onLogin?:()=>void;onArtistLogin?:()=>void;onAccount?:()=>void;loggedIn?:boolean}){
 const{passed}=useScrollY(30);const[open,setOpen]=useState(false);const[active,setActive]=useState("");const[profile,setProfile]=useState<any>(null);const[avatarBroken,setAvatarBroken]=useState(false);
 useEffect(()=>{const sections=LINKS.map(l=>document.querySelector(l.href)).filter(Boolean)as Element[];if(!sections.length)return;const io=new IntersectionObserver(es=>{const v=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(v)setActive(`#${v.target.id}`)},{rootMargin:"-45% 0px -50% 0px",threshold:[.01,.2,.5]});sections.forEach(s=>io.observe(s));return()=>io.disconnect()},[]);
 useEffect(()=>{let alive=true;const sync=()=>{if(!loggedIn){setProfile(null);setAvatarBroken(false);return}getProfile().then(p=>{if(!alive)return;setProfile(p||null);setAvatarBroken(false)}).catch(()=>{});};sync();const onUpdated=()=>sync();window.addEventListener("profile-updated",onUpdated);return()=>{alive=false;window.removeEventListener("profile-updated",onUpdated)}},[loggedIn]);
 useEffect(()=>{setAvatarBroken(false)},[profile?.avatar_url]);
 useEffect(()=>{document.body.style.overflow=open?"hidden":"";return()=>{document.body.style.overflow=""}},[open]);const go=(h:string)=>{setOpen(false);setTimeout(()=>scrollToId(h),open?180:0)};
 const name=(profile?.display_name||"Usuário").trim()||"Usuário";const avatar=profile?.avatar_url||"";const initials=name.split(/\s+/).slice(0,2).map((x:string)=>x[0]).join("").toUpperCase();
 const profileButton=<><div className="h-8 w-8 shrink-0 overflow-hidden rounded-full border border-accent/40 bg-accent-soft">{avatar&&!avatarBroken?<img src={avatar} alt={`Foto de perfil de ${name}`} className="h-full w-full object-cover" onError={()=>setAvatarBroken(true)} referrerPolicy="no-referrer"/>:<div className="grid h-full w-full place-items-center text-[11px] font-extrabold text-accent">{loggedIn?initials:<UserRound className="h-4 w-4"/>}</div>}</div><span className="max-w-[130px] truncate">{loggedIn?name:"Entrar"}</span></>;
 return <><header className={cn("fixed inset-x-0 top-0 z-40 transition-all duration-500",passed?"border-b border-line bg-bg/85 backdrop-blur-xl":"border-b border-transparent bg-transparent")}><nav className="mx-auto flex h-[72px] max-w-[1280px] items-center justify-between gap-6 px-5 sm:px-8"><button type="button" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})} className="group flex items-center gap-2.5" aria-label="Artistas do Bairro — início"><Logo className="h-9 w-9"/><span className="font-display text-[1.15rem] font-extrabold tracking-tight sm:text-[1.35rem]">Artistas do Bairro<span className="text-accent">.</span></span></button><ul className="hidden items-center gap-1 lg:flex">{LINKS.map(l=><li key={l.href}><button type="button" onClick={()=>go(l.href)} className={cn("relative rounded-full px-4 py-2 text-sm font-semibold",active===l.href?"text-accent":"text-ink-soft hover:text-ink")}>{l.label}</button></li>)}</ul><div className="flex items-center gap-2"><button type="button" onClick={loggedIn?onAccount:onLogin} className="hidden items-center gap-2 rounded-full px-4 py-2 text-sm font-semibold text-ink-soft hover:text-accent">{profileButton}</button><button type="button" onClick={onArtistLogin} className="group hidden items-center gap-2 rounded-full bg-ink px-5 py-2.5 text-sm font-bold text-bg dark:bg-accent dark:text-accent-ink sm:flex"><Sparkles className="h-4 w-4"/>Área do artista</button><button type="button" onClick={()=>setOpen(o=>!o)} aria-label={open?"Fechar menu":"Abrir menu"} className="grid h-11 w-11 place-items-center rounded-full border border-line bg-surface lg:hidden">{open?<X className="h-5 w-5"/>:<Menu className="h-5 w-5"/>}</button></div></nav></header><div className={cn("fixed inset-0 z-30 flex flex-col bg-bg px-6 pb-10 pt-24 transition-all duration-500 lg:hidden",open?"pointer-events-auto opacity-100":"pointer-events-none -translate-y-4 opacity-0")}><ul className="relative flex flex-col gap-1">{LINKS.map((l,i)=><li key={l.href} className="border-b border-line"><button type="button" onClick={()=>go(l.href)} className="flex w-full items-baseline gap-3 py-4 text-left font-display text-3xl font-bold"><span className="font-mono text-xs text-accent">0{i+1}</span>{l.label}</button></li>)}</ul><button type="button" onClick={()=>{setOpen(false);loggedIn?onAccount?.():onLogin?.()}} className="relative mt-4 flex w-full items-center gap-3 rounded-2xl border border-line bg-surface px-6 py-4 text-base font-bold">{profileButton}</button><button type="button" onClick={()=>{setOpen(false);onArtistLogin?.()}} className="relative mt-3 w-full rounded-2xl bg-accent px-6 py-4 text-base font-bold text-accent-ink">Área do artista</button></div></>;
}
